#ifndef IMAGEALGORITHM_GLOBAL_H
#define IMAGEALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef IMAGEALGORITHM_LIB
# define IMAGEALGORITHM_EXPORT Q_DECL_EXPORT
#else
# define IMAGEALGORITHM_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEALGORITHM_GLOBAL_H
