#ifndef REPORTWIDGET_GLOBAL_H
#define REPORTWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef REPORTWIDGET_LIB
# define REPORTWIDGET_EXPORT Q_DECL_EXPORT
#else
# define REPORTWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORTWIDGET_GLOBAL_H
